#!/bin/bash
file=$1
clear
#cat $file
tput cup 0 0
x=0
y=0
while true
do
 read templine
 if [ $templine = "up" ]; then
  ((x=x+0))
  ((y=y-2))
  tput cup $x $y
  echo test
 fi
 if [ $templine = "down" ]; then
  ((x=x+0))
  ((y=y+2))
  tput cup $x $y
  echo test2
 fi
done
